 export const CHANGE_START_BUTTON ="CHANGE_START_BUTTON";
 export const CHANGE_SIGNUP_LOGIN = "CHANGE_SIGNUP_LOGIN";
 export const CHANGE_LOGGEDIN ="CHANGE_LOGGEDIN";
 export const CHANGE_OPTION = "CHANGE_OPTION";
export const CHANGE_USER = "CHANGE_USER";